# Generated by Django 4.1.5 on 2023-02-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='Bowels Electric', on_delete=django.db.models.deletion.CASCADE, to='RSVP_system.venue'),
        ),
    ]
