# Generated by Django 4.1.5 on 2023-02-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP_system', '0002_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
